name: Build

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14']
    steps:
        - name: Check out
          uses: actions/checkout@master
        - name: Build
          run: |
            xcodebuild clean build -project VTAutoSlideView.xcodeproj -scheme VTAutoSlideViewDemo -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          env:
            destination: ${{ matrix.destination }}
